@include('layouts.front-header')
<style>
    .site-header nav .right,
    .site-header nav .left .site-hamburgur {
        display: none;
    }
</style>

<main class="content terms">
    <section class="tc-content uSpace">
        <div class="container">
            <h2 class="text-center">TERMS OF USE</h2>
            <p>Relationship Dynamics Institute (“Relationshipdynamics.com”, “RDI” “Evolving Love” “Quadratic” “we,” “us,” or “our”) welcomes you.  We invite you to access and use our websites, including, without limitation, relationshipdynamics.com, quadratic.co, evolvinglove.us, jennifersrussell.com, bryanfranklin.com, and recodelive.com (the “Websites”).</p>  

            <p>We provide visitors to our Websites (“Visitors”) access to the Websites subject to the following Terms of Use, which may be updated by us from time to time without notice to you.  By browsing the public areas or by accessing and using the Websites, you acknowledge that you have read, understood, and agree to be legally bound by these Terms of Use and our Privacy Policy, which is hereby incorporated by reference (collectively, this “Agreement”).  If you do not agree to any of these terms, then please do not use the Websites.</p>

            <p>Any user who registers with us (each, a “Registered User”) and wishes to purchase a product or service through one of our Websites, is agreeing to the terms of this Agreement and the accompanying Terms and Conditions of Purchase with respect to such product or service. In the event of any conflict between the terms of this Agreement and the Terms and Conditions of Purchase, the Terms and Conditions of Purchase shall control.</p>

            <p>THE SECTIONS BELOW TITLED “BINDING ARBITRATION” AND “CLASS ACTION WAIVER” CONTAIN A BINDING ARBITRATION AGREEMENT AND CLASS ACTION WAIVER.  THEY AFFECT YOUR LEGAL RIGHTS.  PLEASE READ THEM CAREFULLY.</p>

            <h4>1. DESCRIPTION AND USE OF OUR WEBSITES</h4>
            <ul>
                <li>We provide Visitors and Registered Users with access to the Services as described below.</li>
                <li>Visitors.</li>
                <li>Registered Users.</li>
                <li>The Relationship Dynamics Institute is under no obligation to accept any individual as a Registered User and may accept or reject any registration in its sole and complete discretion.  In addition, the Relationship Dynamics Institute  may deactivate any account at any time, including, without limitation, if it determines that a Registered User has violated these Terms of Use.</li>
            </ul>

            <h4>2. COMMUNITY GUIDELINES</h4>
            <p>The Relationship Dynamics Institute community, like any community, functions best when its users follow a few simple rules.  By accessing and/or using the Websites, you agree to comply with these community guidelines (the “Community Guidelines”) and that:  </p>
            <ul>
                <li>You will comply with all applicable laws in your use of the Websites and will not use the Websites for any unlawful purpose;</li>
                <li>You will not “stalk,” threaten, or otherwise harass another person;</li>
                <li>If you post any Registered User Content, you will stay on topic;</li>
                <li>You will not impersonate any person or entity or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>
                <li>You will not cover, obscure, block, or in any way interfere with any advertisements and/or safety features (e.g., report abuse button) on the Websites;</li>
                <li>You will not take any action that imposes or may impose (in our sole discretion) an unreasonable or disproportionately large load on our technical infrastructure; and</li>
                <li>We reserve the right, in our sole and absolute discretion, to deny you access to the Websites, or any portion of the Websites, without notice, and to remove any content that does not adhere to these Community Guidelines.</li>
            </ul>

            <h4>3. RESTRICTIONS</h4>
            <p>The Websites are only available for individuals aged 13 years or older.  If you are 13 or older, but under the age of majority in your jurisdiction, you should review this Agreement with your parent or guardian to make sure that you and your parent or guardian understand it.</p>

            <h4>4. SIGN-IN NAME, PASSWORD, UNIQUE IDENTIFIERS</h4>
            <p>During the registration process for Registered Users, we will ask you to create an account, which includes a sign-in name (“Sign-In Name”), a password (“Password”), and perhaps certain additional information that will assist in authenticating your identity when you log-in in the future (“Unique Identifiers”).  When creating your account, you must provide true, accurate, current, and complete information.  Each Sign-In Name and corresponding Password can be used by only one Registered User, and sharing your access credentials with others (especially if they are using your credentials to access our proprietary Content (as defined below)) is a material breach of this Agreement.  You are solely responsible for the confidentiality and use of your Sign-In Name, Password, and Unique Identifiers, as well as for any use, misuse, or communications entered through the Websites using one or more of them.  You will promptly inform us of any need to deactivate a Password or Sign-In Name, or change any Unique Identifier.  We reserve the right to delete or change your Password, Sign-In Name, or Unique Identifier at any time and for any reason and shall have no liability to you for any loss or damage caused by such action.</p>

            <h4>5. FEES AND PAYMENT</h4>
            <p>As consideration for any purchase you make on the Websites, you shall pay The Relationship Dynamics Institute all applicable fees and taxes.  We (or our third-party payment processor) shall authorize your credit card, bank account, or other approved payment facility you provided during the registration process for the full payment of the fees and any applicable taxes, and you hereby consent to the same.  If the mailing address you provided us is in the United States, all payments will be charged and made in U.S. dollars.  If the mailing address you provided us is outside the United States or any of its possessions or territories, all payments will be charged and made in your local currency.</p>

            <p>You must provide current, complete, and accurate billing and credit card information.  You must promptly update all billing information (such as billing address, card number, and expiration date) to keep your account current, complete, and accurate, and you must promptly contact us if your credit card is lost or stolen, or if you become aware of a potential breach of account security (such as an unauthorized disclosure or use of your Sign-In Name or Password).  You hereby authorize the Relationship Dynamics Institute to obtain or determine updated or replacement expiration dates for your credit card in the event that the credit card you provided us expires.  We reserve the right to charge any renewal card issued to you to the same extent as the expired card.  If payment is not received from your credit card issuer, you hereby agree to pay all amounts due upon demand.  You agree to pay all costs of collection, including attorney’s fees and costs, on any outstanding balance.  In certain instances, the issuer of your credit card may charge you a foreign transaction fee or related charges, which you will be responsible to pay.  You are advised to check with your bank and credit card issuer for details.</p>

            <h4>6. INTELLECTUAL PROPERTY</h4>
            <p>The Websites contain material, such as videos, coursework, lesson plans, training modules, photographs, software, text, graphics, images, sound recordings, and other material provided by or on behalf of the Relationship Dynamics Institute (collectively referred to as the “Content”). The Content may be owned by us or third parties.  The Content is protected under both United States and foreign laws.  Unauthorized use of the Content may violate copyright, trademark, and other laws. Visitors may view all publicly-available Content for their own personal, non-commercial use.  Registered Users who have purchased any product or service, may download onto their own machines and view any Content contained in such purchased product or service for their own personal, non-commercial use.  Other than as expressly set forth in the immediately two prior sentences, you have no other rights in or to the Content (other than your own Registered User Content that you post to the Websites), and you will not use the Content except as permitted under this Agreement.  No other use is permitted without the prior written consent of The Relationship Dynamics Institute. The Relationship Dynamics Institute retains all right, title, and interest, including all intellectual property rights, in and to the Content.  You must retain all copyright and other proprietary notices contained in the original Content.  You may not sell, transfer, assign, license, sublicense, or modify the Content or reproduce, display, publicly perform, make a derivative version of, distribute, or otherwise use the Content in any way for any public or commercial purpose.  The use or posting of the Content on any other website, social media page, or in a networked computer environment for any purpose is expressly prohibited.</p>

            <p>If you violate any part of this Agreement, your permission to access and/or use the Content and the Websites automatically terminates and you must immediately destroy any copies you have made of the Content.</p>

            <p>The service marks and logos of the Relationship Dynamics Institute (the “Relationship Dynamics Institute  Marks”) used and displayed on the Websites are registered and unregistered service marks of The Relationship Dynamics Institute.  Other company, product, and service names located on the Websites may be trademarks or service marks owned by others (the “Third-Party Trademarks,” and, collectively with th Marks, thee Relationship Dynamics Institute “Trademarks”).  Nothing on the Websites should be construed as granting, by implication, estoppel, or otherwise, any license or right to use the Trademarks, without our prior written permission specific for each such use.  Use of the Trademarks as part of a link to or from any site is prohibited unless establishment of such a link is approved in advance by us in writing.  All goodwill generated from the use of Relationship Dynamics Institute Marks inures to our benefit.</p>

            <p>Elements of the Websites are protected by trade dress, unfair competition, and other state and federal laws and may not be copied or imitated in whole or in part, by any means, including, but not limited to, the use of framing or mirrors.  None of the Content may be retransmitted without our express, written consent for each and every instance.</p>

            <h4>7. REGISTERED USER CONTENT LICENSES</h4>
            <p>As noted above, the Websites provides Registered Users the ability to post and upload Registered User Content.  You expressly acknowledge and agree that once you submit your Registered User Content for inclusion into the Websites, it will be accessible by others, and that there is no confidentiality or privacy with respect to such Registered User Content, including, without limitation, any personally identifying information that you may make available.  YOU, AND NOT THE RELATIONSHIP DYNAMICS INSTITUTE, ARE ENTIRELY RESPONSIBLE FOR ALL YOUR REGISTERED USER CONTENT THAT YOU UPLOAD, POST, EMAIL, OR OTHERWISE TRANSMIT VIA THE WEBSITES.</p>

            <p>You retain all copyrights and other intellectual property rights in and to your own Registered User Content.  You do, however, hereby grant us and our sublicensees a non-exclusive, royalty-free, freely sublicensable, perpetual license to modify, compile, combine with other content, copy, record, synchronize, transmit, translate, format, distribute, publicly display, publicly perform, and otherwise use or exploit (including for profit) your Registered User Content and all intellectual property and moral rights therein throughout the universe, in each case, by or in any means, methods, media, or technology now known or hereafter devised.  You also grant us and our sublicensees the right, but not the obligation, to use your Registered User Content, your Sign-In Name, name, likeness, and photograph in connection with any use of the related Registered User Content permitted by the previous sentence and/or to advertise and promote the Websites, Relationship Dynamics Institute products and services.  Without limiting the foregoing, you acknowledge and agree that uses of your Registered User Content, name, likeness, and photograph permitted by the foregoing rights and licenses may include the display of such Registered User Content, name, likeness, and photograph adjacent to advertising and other material or content, including for profit.</p>

            <p>If you submit Registered User Content to us, each such submission constitutes a representation and warranty to the Relationship Dynamics Institute that such Registered User Content is your original creation (or that you otherwise have the right to provide the Registered User Content), that you have the rights necessary to grant the license to the Registered User Content under the prior paragraph, and that it and its use by the Relationship Dynamics Institute and its content partners as permitted by this Agreement does not and will not infringe or misappropriate the intellectual property or moral rights of any person or contain any libelous, defamatory, or obscene material or content that violates our Community Guidelines.</p>

            <h4>8. COMMUNICATING WITH US</h4>
            <p>Although we encourage you to email us, we do not want you to, and you should not, email us any content that contains confidential information.  With respect to all emails and communications you send to us, including, but not limited to, feedback, questions, comments, suggestions, and the like, we shall be free to use any ideas, concepts, know-how, or techniques contained in your communications for any purpose whatsoever, including but not limited to, the development, production, and marketing of products and services that incorporate such information without compensation or attribution to you.</p>

            <h4>9. NO WARRANTIES: LIMITATIONS OF LIABILITY</h4>
            <p>THE WEBSITES AND THE CONTENT ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT ANY WARRANTIES OF ANY KIND, INCLUDING THAT THE WEBSITES WILL OPERATE ERROR-FREE OR THAT THE WEBSITES, THEIR SERVERS, OR THE CONTENT ARE FREE OF COMPUTER VIRUSES OR SIMILAR CONTAMINATION OR DESTRUCTIVE FEATURES. WE DISCLAIM ALL WARRANTIES, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF TITLE, MERCHANTABILITY, NON-INFRINGEMENT OF THIRD PARTIES’ RIGHTS, AND FITNESS FOR PARTICULAR PURPOSE AND ANY WARRANTIES ARISING FROM A COURSE OF DEALING, COURSE OF PERFORMANCE, OR USAGE OF TRADE; IN CONNECTION WITH ANY WARRANTY, CONTRACT, OR COMMON LAW TORT CLAIMS: WE AND OUR LICENSORS SHALL NOT BE LIABLE FOR ANY INCIDENTAL OR CONSEQUENTIAL DAMAGES, LOST PROFITS, OR DAMAGES RESULTING FROM LOST DATA OR BUSINESS INTERRUPTION) RESULTING FROM THE USE OR INABILITY TO ACCESS AND USE THE WEBSITES OR THE CONTENT, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND (II) ANY DIRECT DAMAGES THAT YOU MAY SUFFER AS A RESULT OF YOUR USE OF THE WEBSITES OR THE CONTENT SHALL BE LIMITED TO THE FEES YOU HAVE PAID US IN CONNECTION WITH ANY PURCHASES YOU HAVE MADE FROM US DURING THE THREE (3) MONTHS IMMEDIATELY PRECEDING THE EVENTS GIVING RISE TO THE CLAIM.</p>

            <p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES. THEREFORE, SOME OF THE ABOVE LIMITATIONS ON WARRANTIES IN THIS SECTION MAY NOT APPLY TO YOU.</p>

            <p>THE WEBSITES MAY CONTAIN TECHNICAL INACCURACIES OR TYPOGRAPHICAL ERRORS OR OMISSIONS. UNLESS REQUIRED BY APPLICABLE LAWS, WE ARE NOT RESPONSIBLE FOR ANY SUCH TYPOGRAPHICAL, TECHNICAL, OR PRICING ERRORS LISTED ON THE WEBSITES.  THE WEBSITES MAY CONTAIN INFORMATION ON CERTAIN PRODUCTS AND SERVICES, NOT ALL OF WHICH ARE AVAILABLE IN EVERY LOCATION.  A REFERENCE TO A PRODUCT OR SERVICE ON THE WEBSITES DOES NOT IMPLY THAT SUCH PRODUCT OR SERVICE IS OR WILL BE AVAILABLE IN YOUR LOCATION.  WE RESERVE THE RIGHT TO MAKE CHANGES, CORRECTIONS, AND/OR IMPROVEMENTS TO THE WEBSITES AT ANY TIME WITHOUT NOTICE.</p>

            <h4>10. EXTERNAL SITES</h4>
            <p>The Websites may contain links to third-party websites (“External Sites”).  These links are provided solely as a convenience to you and not as an endorsement by us of the content on such External Sites.  The content of such External Sites is developed and provided by others.  You should contact the site administrator or webmaster for those External Sites if you have any concerns regarding such links or any content located on such External Sites.  We are not responsible for the content of any linked External Sites and do not make any representations regarding the content or accuracy of materials on such External Sites.  You should take precautions when downloading files from all websites to protect your computer from viruses and other destructive programs.  If you decide to access linked External Sites, you do so at your own risk.</p>

            <h4>11. REPRESENTATIONS WARRANTIES AND INDEMNIFICATION</h4>
            <p>(a) If you are a Registered User, you hereby represent, warrant, and covenant that:</p>

            <p>You own or have the necessary licenses, rights, consents, and permissions to all trademark, trade secret, copyright, or other proprietary, privacy, and publicity rights in and to your Registered User Content and any other works that you incorporate into your Registered User Content, and all the rights necessary to grant the licenses and permissions you grant hereunder;</p>

            <p>You shall not submit to the Website any Registered User Content that violates our Community Guidelines set forth above or any other term of this Agreement.</p>

            <p>(b) You agree to defend, indemnify, and hold us and our officers, directors, employees, agents, successors, licensees, and assigns harmless from and against any damages, liabilities, losses, expenses, claims, actions, and/or demands, including, without limitation, reasonable legal and accounting fees, arising or resulting from: (i) your breach of this Agreement; (ii) your misuse of the Content or the Websites; and/or (iii) your violation of any third-party rights, including without limitation any copyright, trademark, property, publicity, or privacy right.  We shall provide notice to you of any such claim, suit, or proceeding and shall assist you, at your expense, in defending any such claim, suit, or proceeding.  We reserve the right to assume the exclusive defense and control (at your expense) of any matter that is subject to indemnification under this section.  In such case, you agree to cooperate with any reasonable requests assisting our defense of such matter.</p>

            <h4>12. COMPLIANCE WITH APPLICABLE LAWS</h4>
            <p>The Websites are based in the United States.  We make no claims concerning whether the Content may be downloaded, viewed, or be appropriate for use outside of the United States.  If you access the Websites or the Content from outside of the United States, you do so at your own risk.  Whether inside or outside of the United States, you are solely responsible for ensuring compliance with the laws of your specific jurisdiction.</p>

            <h4>13. TERMINATION OF AGREEMENT</h4>
            <p>We reserve the right, in our sole discretion, to restrict, suspend, or terminate this Agreement and your access to all or any part of the Websites, at any time and for any reason without prior notice or liability.  We reserve the right to change, suspend, or discontinue all or any part of the Websites at any time without prior notice or liability. The following sections shall survive any termination of this Agreement: “Fees and Payment” (until you pay all fees and taxes due hereunder), “Intellectual Property,” “Registered User Content; Licenses,” “Communications with Us,” “No Warranties; Limitation of Liability,” “Representations; Warranties; and Indemnification,” “Termination of the Agreement,” “Controlling Law,” “Binding Arbitration,” “Class Action Waiver,” “Equitable Relief,” and “Miscellaneous.”</p>

            <h4>14. DIGITAL MILLENNIUM COPYRIGHT ACT</h4>
            <p>The Relationship Dynamics Institute respects the intellectual property rights of others and attempts to comply with all relevant laws. We will review all claims of copyright infringement received and remove any Content deemed to have been posted or distributed in violation of any such laws.</p>

            <p>Relationship Dynamics Institute
                23 Regulus Ct<br>
                Alameda, CA 94501<br>
                <a href="">info@relationshipdynamics.com</a>
            </p>

            <p>Our designated agent under the Digital Millennium Copyright Act (the “Act”) for the receipt of any Notification of Claimed Infringement which may be given under that Act is as follows:</p>

            <p>If you believe that your work has been copied on the Websites in a way that constitutes copyright infringement, please provide our agent with notice in accordance with the requirements of the Act, including (i) a description of the copyrighted work that has been infringed and the specific location on the Websites where such work is located; (ii) a description of the location of the original or an authorized copy of the copyrighted work; (iii) your address, telephone number and email address; (iv) a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent or the law; (v) a statement by you, made under penalty of perjury, that the information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf; and (vi) an electronic or physical signature of the owner of the copyright or the person authorized to act on behalf of the owner of the copyright interest.</p>

            <h4>15. CONTROLLING LAW</h4>
            <p>This Agreement and any action related thereto will be governed by the laws of the State of California without regard to its conflict of laws provisions</p>

            <h4>16. BINDING ARBITRATION</h4>
            <p>In the event of a dispute arising under or relating to this Agreement, the Content, or the Websites (each, a “Dispute”), either party may elect to finally and exclusively resolve the dispute by binding arbitration governed by the Federal Arbitration Act (“FAA”).  Any election to arbitrate, at any time, shall be final and binding on the other party. IF EITHER PARTY CHOOSES ARBITRATION, NEITHER PARTY SHALL HAVE THE RIGHT TO LITIGATE SUCH CLAIM IN COURT OR TO HAVE A JURY TRIAL, EXCEPT EITHER PARTY MAY BRING ITS CLAIM IN ITS LOCAL SMALL CLAIMS COURT, IF PERMITTED BY THAT SMALL CLAIMS COURT RULES AND IF WITHIN SUCH COURT’S JURISDICTION.  ARBITRATION IS DIFFERENT FROM COURT, AND DISCOVERY AND APPEAL RIGHTS MAY ALSO BE LIMITED IN ARBITRATION. All disputes will be resolved before a neutral arbitrator selected jointly by the parties, whose decision will be final, except for a limited right of appeal under the FAA. The arbitration shall be commenced and conducted by AAA pursuant to its then current Comprehensive Arbitration Rules and Procedures and in accordance with the Expedited Procedures in those rules,or, where appropriate.. Each party will be responsible for paying any Arbitration filing, administrative, and arbitrator fees in accordance with AAA rules. Judgment on the arbitrator’s award may be entered in any court having jurisdiction. This clause shall not preclude parties from seeking provisional remedies in aid of arbitration from a court of appropriate jurisdiction.  The arbitration may be conducted in person, through the submission of documents, by phone, or online. If conducted in person, the arbitration shall take place in the United States in California. The parties may litigate in court to compel arbitration, to stay a proceeding  pending arbitration, or to confirm, modify, vacate, or enter judgment on the award entered by the arbitrator. The parties shall cooperate in good faith in the voluntary and informal exchange of all non-privileged documents and other information (including electronically stored information) relevant to the Dispute immediately after commencement of the arbitration. As set forth in Section 18 below, nothing in this Agreement will prevent us from seeking injunctive relief in any court of competent jurisdiction as necessary to protect our proprietary interests.</p>

            <h4>17. CLASS ACTION WAIVER</h4>
            <p>You agree that any arbitration or proceeding shall be limited to the Dispute between us and you individually. To the full extent permitted by law, (i) no arbitration or proceeding shall be joined with any other; (ii) there is no right or authority for any Dispute to be arbitrated or resolved on a class action-basis or to utilize class action procedures; and (iii) there is no right or authority for any Dispute to be brought in a purported representative capacity on behalf of the general public or any other persons. YOU AGREE THAT YOU MAY BRING CLAIMS AGAINST US ONLY IN YOUR INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.</p>

            <h4>18. EQUITABLE RELIEF</h4>
            <p>You acknowledge and agree that in the event of a breach or threatened violation of our intellectual property rights and confidential and proprietary information by you, we will suffer irreparable harm and will therefore be entitled to injunctive relief to enforce this Agreement. We may, without waiving any other remedies under this Agreement, seek from any court having jurisdiction any interim, equitable, provisional, or injunctive relief that is necessary to protect our rights and property pending the outcome of the arbitration referenced above. You hereby irrevocably and unconditionally consent to the personal and subject matter jurisdiction of the federal and state courts in the State of California for purposes of any such action by us.</p>

            <h4>19. MISCELLANEOUS</h4>
            <p>Our failure to act on or enforce any provision of the Agreement shall not be construed as a waiver of that provision or any other provision in this Agreement.  No waiver shall be effective against us unless made in writing, and no such waiver shall be construed as a waiver in any other or subsequent instance.  Except as expressly agreed by us and you in writing, this Agreement constitutes the entire Agreement between you and us with respect to the subject matter, and supersedes all previous or contemporaneous agreements, whether written or oral, between the parties with respect to the subject matter.  The section headings are provided merely for convenience and shall not be given any legal import.  This Agreement will inure to the benefit of our successors, assigns, licensees, and sublicensees.</p>

            <h4>CONTACT US</h4>
            <p>If you do not understand or agree with any of these conditions, please do not order this material. If you require further clarification, please contact info@relationshipdynamics.com.</p>
            <p>
                Relationship Dynamics Institute <br>
                23 Regulus Ct<br>
                Alameda CA 94501<br>
            </p>
        </div>
    </section>
</main>
@include('layouts.footer')